# @package model

vision_tokenizer_config:
  encoder_type: siglip2
  encoder_path: checkpoints/SigLIP2-B-d768/encoder
  decoder_path: checkpoints/SigLIP2-B-d768/decoder/model.pt
  stats_path: ${oc.env:RAE_STATS_PATH,checkpoints/SigLIP2-B-d768/robotwin_train_stats.pt}
  dinov3_repo_path: null
  eps: 1.0e-5

video_dit_config:
  in_dim: 768
  out_dim: 768
